/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.ggalmazor.aoc2021;

import static com.github.ggalmazor.aoc2021.lib.Input.readLines;

import com.github.ggalmazor.aoc2021.days.Day1;

public class App {
  public static void main(String[] args) {
    System.out.printf("Day 1 - Part 1: %d%n", new Day1.Part1().apply(readLines(1)));
    System.out.printf("Day 1 - Part 2: %d%n", new Day1.Part2().apply(readLines(1)));
  }
}
