import run1 from './1/solution.mjs';
import run2 from './2/solution.mjs';
import run3 from './3/solution.mjs';
import run4 from './4/solution.mjs';
import run5 from './5/solution.mjs';
import run6 from './6/solution.mjs';
import run7 from './7/solution.mjs';
import run8 from './8/solution.mjs';
import run9 from './9/solution.mjs';
import run10 from './10/solution.mjs';
import run11 from './11/solution.mjs';
import run12 from './12/solution.mjs';

run1();
run2();
run3();
run4();
run5();
run6();
run7();
run8();
run9();
run10();
run11();
run12();
